USE [master]
GO

/****** Object:  Database [ManagerGame]    Script Date: 10.10.2013 19:39:49 ******/
CREATE DATABASE [ManagerGame] ON  PRIMARY 
( NAME = N'ManagerGame', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\ManagerGame.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ManagerGame_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\ManagerGame_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ManagerGame] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ManagerGame].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ManagerGame] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ManagerGame] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ManagerGame] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ManagerGame] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ManagerGame] SET ARITHABORT OFF 
GO

ALTER DATABASE [ManagerGame] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ManagerGame] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ManagerGame] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ManagerGame] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ManagerGame] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ManagerGame] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ManagerGame] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ManagerGame] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ManagerGame] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ManagerGame] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ManagerGame] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ManagerGame] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ManagerGame] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ManagerGame] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ManagerGame] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ManagerGame] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ManagerGame] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ManagerGame] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ManagerGame] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ManagerGame] SET  MULTI_USER 
GO

ALTER DATABASE [ManagerGame] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ManagerGame] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ManagerGame] SET  READ_WRITE 
GO

